# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 298b0b7f9e67564c4003b99348c6bec70d5a5a762cbd69035c7484bd63855b3e8dbd153f3b2b9bcc36701bfea959203fc52ebc107da677c62db65ed833322e3f

test:
  secret_key_base: 548b74328be5d34f04d010dd8d8353f4fc057118eeb8460c240ca13d1480e05bdc7ccd12a6cddfe7452b3616f9f03e574b16aed1b66dada2492b0e2a846a7b36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
